kind: Secret
apiVersion: v1
metadata:
  name: minio-credentials
  namespace: sglang
data:
  MINIO_ACCESS_KEY: ZndlZ1Z6Vnd1UjJYQlJNOVhVbHgK
  MINIO_SECRET_KEY: ZGgzUGNHWkRWclRob0ZRWUE3TTZTOVlpUFRlYkMxeU8zZGo1ODdvZQo=
type: Opaque
