kind: Secret
apiVersion: v1
metadata:
  name: minio-credentials
  namespace: sglang
data:
  MINIO_ACCESS_KEY: RkJvTWF0Ykxta1AwVnY4NVNDWXoK
  MINIO_SECRET_KEY: UXJoSGViWDhKU0NUTWVqRXZIUmlYbmk1M2tnVkxqOG1iNnZGRGFtdgo=
type: Opaque
