kind: Secret
apiVersion: v1
metadata:
  name: minio-credentials
  namespace: llm-inference
data:
  # Access Key: minio env变量里面有
  MINIO_ACCESS_KEY: M2p2RjBMblg4eGhXUEJxMUZ2SUE=
  # Secret Key: minio env变量里面有
  MINIO_SECRET_KEY: cUlYVWRhME01Yk81NXJGdW9LbkFkczBLS29uVmxMeVFRdWFUMUJTMg==
type: Opaque
