apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qwen3-8b-model-pvc-sglang
  namespace: sglang
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi
